name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3
      - name: Check Node v
        run: node -v
      - name: Install Dependencies
        run: npm install --frozen-lockfile
      - name: Build
        run: npm run build
      - name: zip create
        run: zip -qq -r ./build.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-region: ap-northeast-2c
      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./build.zip s3://mycafeflowbucket/cafeflow_front/build.zip
      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment
          --application-name cafeflow-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name cafeflow-codedeploy-group
          --s3-location bucket=mycafeflowbucket,bundleType=zip,key=build.zip
