version: 0.0
os: linux
files:
  - source: /build/ # 만약 빌드 결과물이 'build' 디렉토리에 있다면 이렇게 변경합니다.
    destination: /home/ubuntu/CafeFlow_front
    overwrite: yes
permissions:
  - object: /home/ubuntu/CafeFlow_front
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 1000
      runas: root
